resources:
  - type: module
    url: /local/community/lovelace-better-thermostat/dist/better-thermostat.js
  - type: js
    url: /local/dual-thermostat/dist/dual-thermostat.js?v=1
title: ''
views:
  - title: 主页
    path: home
    icon: 'mdi:home'
    theme: 黑-蓝
    badges: []
    cards:
      - type: weather-forecast
        entity: weather.met_home
        name: 杭州
      - type: entities
        entities:
          - entity: binary_sensor.updater
          - entity: automation.set_ha_theme_for_day_and_night
  - path: device
    title: 1号楼设备组
    icon: ''
    panel: false
    badges: []
    cards:
      - entities:
          - entity: sensor.house1_room1_humidity
            name: 温度
          - entity: sensor.house1_room1_illuminance
            name: 亮度
          - entity: sensor.house1_room1_nh3
            name: 氨气
          - entity: sensor.house1_room1_temperature
            name: 温度
          - entity: sensor.house1_room1_pm25
            name: pm2.5
          - entity: climate.house1_room1
            name: 空调
          - entity: fan.house1_room1
            name: 风扇
          - entity: light.house1_room1
            name: 灯光
          - entity: switch.house1_room1_cool
            name: 制冷开关
          - entity: switch.house1_room1_heater
            name: 加热开关
          - entity: switch.house1_room1_switch
            name: 开关
        show_header_toggle: false
        title: house1_room1
        type: entities
        theme: 灰-绿
      - entities:
          - entity: sensor.house1_room2_humidity
            name: 温度
          - entity: sensor.house1_room2_illuminance
            name: 亮度
          - entity: sensor.house1_room2_nh3
            name: 氨气
          - entity: sensor.house1_room2_temperature
            name: 温度
          - entity: sensor.house1_room2_pm25
            name: pm2.5
          - entity: climate.house1_room2
            name: 空调
          - entity: fan.house1_room2
            name: 风扇
          - entity: light.house1_room2
            name: 灯光
          - entity: switch.house1_room2_cool
            name: 制冷开关
          - entity: switch.house1_room2_heater
            name: 加热开关
          - entity: switch.house1_room2_switch
            name: 开关
        show_header_toggle: false
        title: house1_room2
        type: entities
        theme: 灰-绿
      - entities:
          - entity: sensor.house1_room3_humidity
            name: 温度
          - entity: sensor.house1_room3_illuminance
            name: 亮度
          - entity: sensor.house1_room3_nh3
            name: 氨气
          - entity: sensor.house1_room3_temperature
            name: 温度
          - entity: sensor.house1_room3_pm25
            name: pm2.5
          - entity: climate.house1_room3
            name: 空调
          - entity: fan.house1_room3
            name: 风扇
          - entity: light.house1_room3
            name: 灯光
          - entity: switch.house1_room3_cool
            name: 制冷开关
          - entity: switch.house1_room3_heater
            name: 加热开关
          - entity: switch.house1_room3_switch
            name: 开关
        show_header_toggle: false
        title: house1_room3
        type: entities
        theme: 灰-绿
      - entities:
          - entity: sensor.house1_room4_humidity
            name: 温度
          - entity: sensor.house1_room4_illuminance
            name: 亮度
          - entity: sensor.house1_room4_nh3
            name: 氨气
          - entity: sensor.house1_room4_temperature
            name: 温度
          - entity: sensor.house1_room4_pm25
            name: pm2.5
          - entity: climate.house1_room4
            name: 空调
          - entity: fan.house1_room4
            name: 风扇
          - entity: light.house1_room4
            name: 灯光
          - entity: switch.house1_room4_cool
            name: 制冷开关
          - entity: switch.house1_room4_heater
            name: 加热开关
          - entity: switch.house1_room4_switch
            name: 开关
        show_header_toggle: false
        title: house1_room4
        type: entities
        theme: 灰-绿
      - entities:
          - entity: sensor.house1_room5_humidity
            name: 温度
          - entity: sensor.house1_room5_illuminance
            name: 亮度
          - entity: sensor.house1_room5_nh3
            name: 氨气
          - entity: sensor.house1_room5_temperature
            name: 温度
          - entity: sensor.house1_room5_pm25
            name: pm2.5
          - entity: climate.house1_room5
            name: 空调
          - entity: fan.house1_room5
            name: 风扇
          - entity: light.house1_room5
            name: 灯光
          - entity: switch.house1_room5_cool
            name: 制冷开关
          - entity: switch.house1_room5_heater
            name: 加热开关
          - entity: switch.house1_room5_switch
            name: 开关
        show_header_toggle: false
        title: house1_room5
        type: entities
        theme: 灰-绿
      - entities:
          - entity: sensor.house1_room6_humidity
            name: 温度
          - entity: sensor.house1_room6_illuminance
            name: 亮度
          - entity: sensor.house1_room6_nh3
            name: 氨气
          - entity: sensor.house1_room6_temperature
            name: 温度
          - entity: sensor.house1_room6_pm25
            name: pm2.5
          - entity: climate.house1_room6
            name: 空调
          - entity: fan.house1_room6
            name: 风扇
          - entity: light.house1_room6
            name: 灯光
          - entity: switch.house1_room6_cool
            name: 制冷开关
          - entity: switch.house1_room6_heater
            name: 加热开关
          - entity: switch.house1_room6_switch
            name: 开关
        show_header_toggle: false
        title: house1_room6
        type: entities
        theme: 灰-绿
      - entities:
          - entity: sensor.house1_room7_humidity
            name: 温度
          - entity: sensor.house1_room7_illuminance
            name: 亮度
          - entity: sensor.house1_room7_nh3
            name: 氨气
          - entity: sensor.house1_room7_temperature
            name: 温度
          - entity: sensor.house1_room7_pm25
            name: pm2.5
          - entity: climate.house1_room7
            name: 空调
          - entity: fan.house1_room7
            name: 风扇
          - entity: light.house1_room7
            name: 灯光
          - entity: switch.house1_room7_cool
            name: 制冷开关
          - entity: switch.house1_room7_heater
            name: 加热开关
          - entity: switch.house1_room7_switch
            name: 开关
        show_header_toggle: false
        title: house1_room7
        type: entities
        theme: 灰-绿
      - entities:
          - entity: sensor.house1_room8_humidity
            name: 温度
          - entity: sensor.house1_room8_illuminance
            name: 亮度
          - entity: sensor.house1_room8_nh3
            name: 氨气
          - entity: sensor.house1_room8_temperature
            name: 温度
          - entity: sensor.house1_room8_pm25
            name: pm2.5
          - entity: climate.house1_room8
            name: 空调
          - entity: fan.house1_room8
            name: 风扇
          - entity: light.house1_room8
            name: 灯光
          - entity: switch.house1_room8_cool
            name: 制冷开关
          - entity: switch.house1_room8_heater
            name: 加热开关
          - entity: switch.house1_room8_switch
            name: 开关
        show_header_toggle: false
        title: house1_room8
        type: entities
        theme: 灰-绿
      - entities:
          - entity: sensor.house1_room9_humidity
            name: 温度
          - entity: sensor.house1_room9_illuminance
            name: 亮度
          - entity: sensor.house1_room9_nh3
            name: 氨气
          - entity: sensor.house1_room9_temperature
            name: 温度
          - entity: sensor.house1_room9_pm25
            name: pm2.5
          - entity: climate.house1_room9
            name: 空调
          - entity: fan.house1_room9
            name: 风扇
          - entity: light.house1_room9
            name: 灯光
          - entity: switch.house1_room9_cool
            name: 制冷开关
          - entity: switch.house1_room9_heater
            name: 加热开关
          - entity: switch.house1_room9_switch
            name: 开关
        show_header_toggle: false
        title: house1_room9
        type: entities
        theme: 灰-绿
  - icon: ''
    path: house1
    title: 1号楼监控
    badges: []
    cards:
      - cards:
          - aspect_ratio: 60%
            columns: 3
            entity: climate.house1_room1
            name: room1
            theme: 明亮蓝
            type: thermostat
          - entities:
              - entity: sensor.house1_room1_temperature
                name: 温度
              - entity: sensor.house1_room1_humidity
                name: 湿度
              - entity: sensor.house1_room1_pm25
                name: PM2.5
              - entity: sensor.house1_room1_illuminance
                name: 亮度
              - entity: sensor.house1_room1_nh3
                name: 氨气
            theme: 灰-绿
            type: glance
          - aspect_ratio: 60%
            camera_image: camera.zi_tai_jian_ce
            camera_view: live
            entities:
              - entity: switch.house1_room1_switch
              - entity: light.house1_room1
            image: >-
              https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
            type: picture-glance
        type: vertical-stack
      - cards:
          - aspect_ratio: 60%
            columns: 3
            entity: climate.house1_room2
            name: room2
            theme: 明亮蓝
            type: thermostat
          - entities:
              - entity: sensor.house1_room2_temperature
                name: 温度
              - entity: sensor.house1_room2_humidity
                name: 湿度
              - entity: sensor.house1_room2_pm25
                name: PM2.5
              - entity: sensor.house1_room2_illuminance
                name: 亮度
              - entity: sensor.house1_room2_nh3
                name: 氨气
            theme: 灰-绿
            type: glance
          - aspect_ratio: 60%
            camera_image: camera.zi_tai_jian_ce
            camera_view: live
            entities:
              - entity: switch.house1_room2_switch
              - entity: light.house1_room2
            image: >-
              https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
            type: picture-glance
        type: vertical-stack
      - cards:
          - aspect_ratio: 60%
            columns: 3
            entity: climate.house1_room3
            name: room3
            theme: 明亮蓝
            type: thermostat
          - entities:
              - entity: sensor.house1_room3_temperature
                name: 温度
              - entity: sensor.house1_room3_humidity
                name: 湿度
              - entity: sensor.house1_room3_pm25
                name: PM2.5
              - entity: sensor.house1_room3_illuminance
                name: 亮度
              - entity: sensor.house1_room3_nh3
                name: 氨气
            theme: 灰-绿
            type: glance
          - aspect_ratio: 60%
            camera_image: camera.zi_tai_jian_ce
            camera_view: live
            entities:
              - entity: switch.house1_room3_switch
              - entity: light.house1_room3
            image: >-
              https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
            type: picture-glance
        type: vertical-stack
      - cards:
          - aspect_ratio: 60%
            columns: 3
            entity: climate.house1_room4
            name: room4
            theme: 明亮蓝
            type: thermostat
          - entities:
              - entity: sensor.house1_room4_temperature
                name: 温度
              - entity: sensor.house1_room4_humidity
                name: 湿度
              - entity: sensor.house1_room4_pm25
                name: PM2.5
              - entity: sensor.house1_room4_illuminance
                name: 亮度
              - entity: sensor.house1_room4_nh3
                name: 氨气
            theme: 灰-绿
            type: glance
          - aspect_ratio: 60%
            camera_image: camera.zi_tai_jian_ce
            camera_view: live
            entities:
              - entity: switch.house1_room4_switch
              - entity: light.house1_room4
            image: >-
              https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
            type: picture-glance
        type: vertical-stack
      - cards:
          - aspect_ratio: 60%
            columns: 3
            entity: climate.house1_room5
            name: room5
            theme: 明亮蓝
            type: thermostat
          - entities:
              - entity: sensor.house1_room5_temperature
                name: 温度
              - entity: sensor.house1_room5_humidity
                name: 湿度
              - entity: sensor.house1_room5_pm25
                name: PM2.5
              - entity: sensor.house1_room5_illuminance
                name: 亮度
              - entity: sensor.house1_room5_nh3
                name: 氨气
            theme: 灰-绿
            type: glance
          - aspect_ratio: 60%
            camera_image: camera.zi_tai_jian_ce
            camera_view: live
            entities:
              - entity: switch.house1_room5_switch
              - entity: light.house1_room5
            image: >-
              https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
            type: picture-glance
        type: vertical-stack
      - cards:
          - aspect_ratio: 60%
            columns: 3
            entity: climate.house1_room6
            name: room6
            theme: 明亮蓝
            type: thermostat
          - entities:
              - entity: sensor.house1_room6_temperature
                name: 温度
              - entity: sensor.house1_room6_humidity
                name: 湿度
              - entity: sensor.house1_room6_pm25
                name: PM2.5
              - entity: sensor.house1_room6_illuminance
                name: 亮度
              - entity: sensor.house1_room6_nh3
                name: 氨气
            theme: 灰-绿
            type: glance
          - aspect_ratio: 60%
            camera_image: camera.zi_tai_jian_ce
            camera_view: live
            entities:
              - entity: switch.house1_room6_switch
              - entity: light.house1_room6
            image: >-
              https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
            type: picture-glance
        type: vertical-stack
      - cards:
          - aspect_ratio: 60%
            columns: 3
            entity: climate.house1_room7
            name: room7
            theme: 明亮蓝
            type: thermostat
          - entities:
              - entity: sensor.house1_room7_temperature
                name: 温度
              - entity: sensor.house1_room7_humidity
                name: 湿度
              - entity: sensor.house1_room7_pm25
                name: PM2.5
              - entity: sensor.house1_room7_illuminance
                name: 亮度
              - entity: sensor.house1_room7_nh3
                name: 氨气
            theme: 灰-绿
            type: glance
          - aspect_ratio: 60%
            camera_image: camera.zi_tai_jian_ce
            camera_view: live
            entities:
              - entity: switch.house1_room7_switch
              - entity: light.house1_room7
            image: >-
              https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
            type: picture-glance
        type: vertical-stack